mixed-port: 7890
tproxy-port: 7893
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: /data/mihomo/ui

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.hen-ladon.ts.net"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "+.hen-ladon.ts.net": "100.100.100.100"
    "geosite:cn,private":
      - https://doh.pub/dns-query

proxies:
  - name: "test-direct"
    type: direct

proxy-groups:
  - name: "ðŸš€ èŠ‚ç‚¹é€‰æ‹©"
    type: select
    proxies:
      - test-direct
      - DIRECT

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
